### ISSUE TITLE
Alias `man n` to `man-n`

### ISSUE THREAD

**Issue by wooorm** [man-n/man-n#9]
Similar to what [`github/hub`](https://github.com/github/hub#aliasing) does.

Caveat: there’s a [difference](https://en.wikipedia.org/wiki/Man_page#Usage) in how sections are passed to man(1), but maybe support for solaris can initially be ignored.

Also: maybe a simple `man-n --link` (and `man-n --unlink`) should be added?

**Comment by yoshuawuyts** [comment]
I think `man-n -{--link,--unlink}` is a good one to add, given that `alias man=man-n` wouldn't work. Since neither of us uses Solaris as their main OS I'm +1 for not supporting it; if anyone wants to fix breakage they're welcome to add patches (wouldn't know how to test it / don't think it matters too much).

**Comment by wooorm** [comment]
Almost got the alias/overwrite working!

For now, lets indeed ignore solaris/&c., and passing more arguments into `man`.

Few minutes!

**Comment by wooorm** [comment]
Refactored!
